#JDBC基本配置
spring:
  # 配置数据源
  datasource:
    #    financial-task:
    gbw:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://172.16.200.192:3306/cngongbao_old_gongbaowang?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: DhvUGkENahLUwCh@1
      druid:
        initial: 5
        max-active: 10


